// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      activity_events: {
        Row: {
          id: string
          organization_id: string
          item_id: string | null
          actor_id: string | null
          event_type: 'created' | 'state_changed' | 'completed' | 'responsible_role_added' | 'responsible_role_removed' | 'primary_role_changed' | 'assigned_user_added' | 'assigned_user_removed' | 'primary_user_changed' | 'moved_list' | 'tag_added' | 'tag_removed'
          payload: Json
          effective_at: string
          recorded_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          item_id?: string | null
          actor_id?: string | null
          event_type: 'created' | 'state_changed' | 'completed' | 'responsible_role_added' | 'responsible_role_removed' | 'primary_role_changed' | 'assigned_user_added' | 'assigned_user_removed' | 'primary_user_changed' | 'moved_list' | 'tag_added' | 'tag_removed'
          payload?: Json
          effective_at?: string
          recorded_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          item_id?: string | null
          actor_id?: string | null
          event_type?: 'created' | 'state_changed' | 'completed' | 'responsible_role_added' | 'responsible_role_removed' | 'primary_role_changed' | 'assigned_user_added' | 'assigned_user_removed' | 'primary_user_changed' | 'moved_list' | 'tag_added' | 'tag_removed'
          payload?: Json
          effective_at?: string
          recorded_at?: string
        }
      }
      ai_captures: {
        Row: {
          id: string
          organization_id: string
          user_id: string | null
          raw_input: string
          parsed: Json
          provider: string | null
          model: string | null
          confidence: number | null
          required_clarification: boolean
          resulting_item_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          user_id?: string | null
          raw_input: string
          parsed?: Json
          provider?: string | null
          model?: string | null
          confidence?: number | null
          required_clarification?: boolean
          resulting_item_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          user_id?: string | null
          raw_input?: string
          parsed?: Json
          provider?: string | null
          model?: string | null
          confidence?: number | null
          required_clarification?: boolean
          resulting_item_id?: string | null
          created_at?: string
        }
      }
      checklist_items: {
        Row: {
          id: string
          organization_id: string
          item_id: string
          text: string
          is_done: boolean
          position: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          item_id: string
          text: string
          is_done?: boolean
          position?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          item_id?: string
          text?: string
          is_done?: boolean
          position?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      folders: {
        Row: {
          id: string
          organization_id: string
          name: string
          color: string | null
          position: number
          is_archived: boolean
          created_by: string | null
          created_at: string
          updated_at: string
          project_id: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          color?: string | null
          position?: number
          is_archived?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
          project_id: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          color?: string | null
          position?: number
          is_archived?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
          project_id?: string
        }
      }
      invitations: {
        Row: {
          id: string
          organization_id: string
          email: string
          role: 'owner' | 'admin' | 'member'
          token: string
          status: 'pending' | 'accepted' | 'revoked'
          invited_by: string | null
          accepted_by: string | null
          expires_at: string
          created_at: string
          accepted_at: string | null
        }
        Insert: {
          id?: string
          organization_id: string
          email: string
          role?: 'owner' | 'admin' | 'member'
          token: string
          status?: 'pending' | 'accepted' | 'revoked'
          invited_by?: string | null
          accepted_by?: string | null
          expires_at?: string
          created_at?: string
          accepted_at?: string | null
        }
        Update: {
          id?: string
          organization_id?: string
          email?: string
          role?: 'owner' | 'admin' | 'member'
          token?: string
          status?: 'pending' | 'accepted' | 'revoked'
          invited_by?: string | null
          accepted_by?: string | null
          expires_at?: string
          created_at?: string
          accepted_at?: string | null
        }
      }
      item_assigned_users: {
        Row: {
          id: string
          organization_id: string
          item_id: string
          user_id: string
          is_primary: boolean
          assigned_via: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          item_id: string
          user_id: string
          is_primary?: boolean
          assigned_via?: string
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          item_id?: string
          user_id?: string
          is_primary?: boolean
          assigned_via?: string
          created_by?: string | null
          created_at?: string
        }
      }
      item_collaborators: {
        Row: {
          id: string
          organization_id: string
          item_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          item_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          item_id?: string
          user_id?: string
          created_at?: string
        }
      }
      item_responsible_roles: {
        Row: {
          id: string
          organization_id: string
          item_id: string
          role_id: string
          is_primary: boolean
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          item_id: string
          role_id: string
          is_primary?: boolean
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          item_id?: string
          role_id?: string
          is_primary?: boolean
          created_by?: string | null
          created_at?: string
        }
      }
      item_tags: {
        Row: {
          organization_id: string
          item_id: string
          tag_id: string
        }
        Insert: {
          organization_id: string
          item_id: string
          tag_id: string
        }
        Update: {
          organization_id?: string
          item_id?: string
          tag_id?: string
        }
      }
      items: {
        Row: {
          id: string
          organization_id: string
          type: 'task' | 'note' | 'meeting'
          state: 'captured' | 'committed' | 'in_progress' | 'done' | 'snoozed' | 'backlog'
          title: string
          body: string | null
          priority: 'none' | 'low' | 'medium' | 'high' | 'urgent'
          list_id: string | null
          due_at: string | null
          remind_at: string | null
          snoozed_until: string | null
          completed_at: string | null
          is_reminder: boolean
          waiting_on: string | null
          is_reference: boolean
          source: string
          ai_confidence: number | null
          created_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          search: unknown | null
          definition_of_done: string | null
          start_at: string | null
          time_estimate_minutes: number | null
          nudge_at: string | null
        }
        Insert: {
          id?: string
          organization_id: string
          type: 'task' | 'note' | 'meeting'
          state?: 'captured' | 'committed' | 'in_progress' | 'done' | 'snoozed' | 'backlog'
          title: string
          body?: string | null
          priority?: 'none' | 'low' | 'medium' | 'high' | 'urgent'
          list_id?: string | null
          due_at?: string | null
          remind_at?: string | null
          snoozed_until?: string | null
          completed_at?: string | null
          is_reminder?: boolean
          waiting_on?: string | null
          is_reference?: boolean
          source?: string
          ai_confidence?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          definition_of_done?: string | null
          start_at?: string | null
          time_estimate_minutes?: number | null
        }
        Update: {
          id?: string
          organization_id?: string
          type?: 'task' | 'note' | 'meeting'
          state?: 'captured' | 'committed' | 'in_progress' | 'done' | 'snoozed' | 'backlog'
          title?: string
          body?: string | null
          priority?: 'none' | 'low' | 'medium' | 'high' | 'urgent'
          list_id?: string | null
          due_at?: string | null
          remind_at?: string | null
          snoozed_until?: string | null
          completed_at?: string | null
          is_reminder?: boolean
          waiting_on?: string | null
          is_reference?: boolean
          source?: string
          ai_confidence?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          definition_of_done?: string | null
          start_at?: string | null
          time_estimate_minutes?: number | null
        }
      }
      lists: {
        Row: {
          id: string
          organization_id: string
          name: string
          description: string | null
          color: string | null
          is_archived: boolean
          created_by: string | null
          created_at: string
          updated_at: string
          folder_id: string | null
          position: number
          project_id: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          description?: string | null
          color?: string | null
          is_archived?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
          folder_id?: string | null
          position?: number
          project_id: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          description?: string | null
          color?: string | null
          is_archived?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
          folder_id?: string | null
          position?: number
          project_id?: string
        }
      }
      meeting_details: {
        Row: {
          item_id: string
          organization_id: string
          starts_at: string | null
          ends_at: string | null
          location: string | null
          agenda: string | null
          outcome_notes: string | null
          external_calendar_id: string | null
          external_provider: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          item_id: string
          organization_id: string
          starts_at?: string | null
          ends_at?: string | null
          location?: string | null
          agenda?: string | null
          outcome_notes?: string | null
          external_calendar_id?: string | null
          external_provider?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          item_id?: string
          organization_id?: string
          starts_at?: string | null
          ends_at?: string | null
          location?: string | null
          agenda?: string | null
          outcome_notes?: string | null
          external_calendar_id?: string | null
          external_provider?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      organization_members: {
        Row: {
          id: string
          organization_id: string
          user_id: string
          role: 'owner' | 'admin' | 'member'
          is_active: boolean
          invited_by: string | null
          invited_at: string | null
          joined_at: string
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          user_id: string
          role?: 'owner' | 'admin' | 'member'
          is_active?: boolean
          invited_by?: string | null
          invited_at?: string | null
          joined_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          user_id?: string
          role?: 'owner' | 'admin' | 'member'
          is_active?: boolean
          invited_by?: string | null
          invited_at?: string | null
          joined_at?: string
          created_at?: string
        }
      }
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          is_personal: boolean
          team_enabled: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          is_personal?: boolean
          team_enabled?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          is_personal?: boolean
          team_enabled?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          display_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          organization_id: string
          name: string
          color: string | null
          position: number
          is_archived: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          color?: string | null
          position?: number
          is_archived?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          color?: string | null
          position?: number
          is_archived?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      role_assignments: {
        Row: {
          id: string
          organization_id: string
          role_id: string
          user_id: string
          valid_from: string
          valid_to: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          role_id: string
          user_id: string
          valid_from?: string
          valid_to?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          role_id?: string
          user_id?: string
          valid_from?: string
          valid_to?: string | null
          created_by?: string | null
          created_at?: string
        }
      }
      roles: {
        Row: {
          id: string
          organization_id: string
          name: string
          description: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          description?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          description?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      saved_views: {
        Row: {
          id: string
          organization_id: string
          owner_id: string | null
          name: string
          filter: Json
          is_system: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          owner_id?: string | null
          name: string
          filter?: Json
          is_system?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          owner_id?: string | null
          name?: string
          filter?: Json
          is_system?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      tags: {
        Row: {
          id: string
          organization_id: string
          name: string
          color: string | null
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          color?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          color?: string | null
          created_at?: string
        }
      }
    }
    Enums: {
      activity_event_type: 'created' | 'state_changed' | 'completed' | 'responsible_role_added' | 'responsible_role_removed' | 'primary_role_changed' | 'assigned_user_added' | 'assigned_user_removed' | 'primary_user_changed' | 'moved_list' | 'tag_added' | 'tag_removed'
      invitation_status: 'pending' | 'accepted' | 'revoked'
      item_state: 'captured' | 'committed' | 'in_progress' | 'done' | 'snoozed' | 'backlog'
      item_type: 'task' | 'note' | 'meeting'
      org_member_role: 'owner' | 'admin' | 'member'
      priority: 'none' | 'low' | 'medium' | 'high' | 'urgent'
    }
  }
}

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"]
export type InsertDto<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"]
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T]
