// Generate a TypeScript `Database` type by introspecting the live schema.
// Usage: PGHOST=... PGPASSWORD=... node scripts/gen-types.mjs > src/lib/supabase/database.types.ts
import pg from 'pg'

const client = new pg.Client({
  host: process.env.PGHOST,
  port: Number(process.env.PGPORT || 5432),
  user: process.env.PGUSER || 'postgres',
  password: process.env.PGPASSWORD,
  database: process.env.PGDATABASE || 'postgres',
  ssl: { rejectUnauthorized: false },
})
await client.connect()

const enumRows = (
  await client.query(`
    select t.typname as name, e.enumlabel as label
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
    order by t.typname, e.enumsortorder`)
).rows
const enums = {}
for (const r of enumRows) (enums[r.name] ||= []).push(r.label)

const colRows = (
  await client.query(`
    select c.table_name, c.column_name, c.udt_name, c.is_nullable,
           c.column_default, c.is_generated
    from information_schema.columns c
    join information_schema.tables t
      on t.table_schema = c.table_schema and t.table_name = c.table_name
    where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
    order by c.table_name, c.ordinal_position`)
).rows
const tables = {}
for (const r of colRows) (tables[r.table_name] ||= []).push(r)

const enumUnion = (vals) => vals.map((v) => `'${v}'`).join(' | ')

function tsType(udt) {
  if (enums[udt]) return enumUnion(enums[udt])
  switch (udt) {
    case 'uuid':
    case 'text':
    case 'varchar':
    case 'bpchar':
    case 'char':
    case 'timestamptz':
    case 'timestamp':
    case 'date':
    case 'time':
      return 'string'
    case 'bool':
      return 'boolean'
    case 'int2':
    case 'int4':
    case 'int8':
    case 'numeric':
    case 'float4':
    case 'float8':
      return 'number'
    case 'jsonb':
    case 'json':
      return 'Json'
    default:
      return 'unknown'
  }
}

let out = '// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.\n'
out += 'export type Json =\n  | string\n  | number\n  | boolean\n  | null\n  | { [key: string]: Json | undefined }\n  | Json[]\n\n'
out += 'export interface Database {\n  public: {\n    Tables: {\n'
for (const [t, cols] of Object.entries(tables)) {
  out += `      ${t}: {\n        Row: {\n`
  for (const c of cols) {
    out += `          ${c.column_name}: ${tsType(c.udt_name)}${c.is_nullable === 'YES' ? ' | null' : ''}\n`
  }
  out += '        }\n        Insert: {\n'
  for (const c of cols) {
    if (c.is_generated === 'ALWAYS') continue
    const optional = c.is_nullable === 'YES' || c.column_default !== null
    out += `          ${c.column_name}${optional ? '?' : ''}: ${tsType(c.udt_name)}${c.is_nullable === 'YES' ? ' | null' : ''}\n`
  }
  out += '        }\n        Update: {\n'
  for (const c of cols) {
    if (c.is_generated === 'ALWAYS') continue
    out += `          ${c.column_name}?: ${tsType(c.udt_name)}${c.is_nullable === 'YES' ? ' | null' : ''}\n`
  }
  out += '        }\n      }\n'
}
out += '    }\n    Enums: {\n'
for (const [n, vals] of Object.entries(enums)) out += `      ${n}: ${enumUnion(vals)}\n`
out += '    }\n  }\n}\n\n'
out += 'export type Tables<T extends keyof Database["public"]["Tables"]> =\n  Database["public"]["Tables"][T]["Row"]\n'
out += 'export type InsertDto<T extends keyof Database["public"]["Tables"]> =\n  Database["public"]["Tables"][T]["Insert"]\n'
out += 'export type Enums<T extends keyof Database["public"]["Enums"]> =\n  Database["public"]["Enums"][T]\n'

process.stdout.write(out)
await client.end()
